generator.yaml, pkg/resource/table/conditions.go, pkg/resource/table/hooks.go, pkg/resource/table/sdk.go, templates/hooks/table/sdk_delete_pre_build_request.go.tpl, templates/hooks/table/sdk_read_one_post_set_output.go.tpl, templates/hooks/table/sdk_update_pre_build_request.go.tpl, test/e2e/.gitignore, test/e2e/__init__.py, test/e2e/bootstrap_resources.py, test/e2e/conftest.py, test/e2e/replacement_values.py, test/e2e/requirements.txt, test/e2e/resources/table_forums.yaml, test/e2e/service_bootstrap.py, test/e2e/service_cleanup.py, test/e2e/tests/test_table.py
Part of https://github.com/aws-controllers-k8s/community/issues/803
Description of changes
- Add custom hooks, terminalCodes, printcomns to `Table` resource in `generator.yaml`
- Add e2e tests for `Table` create and delete operations
=> Add `Table` resource custom hooks, terminalCodes and e2e tests

generator.yaml, pkg/resource/backup/manager.go, pkg/resource/global_table/custom_api.go, pkg/resource/global_table/manager.go, pkg/resource/global_table/sdk.go, pkg/resource/table/manager.go, test/e2e/resources/global_table.yaml, test/e2e/tests/test_global_table.py
Part of https://github.com/aws-controllers-k8s/community/issues/803
Description of changes
- Add custom hooks, terminalCodes to `GlobalTable` resource in `generator.yaml`
- Add e2e tests for `GlobalTable` create and delete operations
=> Add `GlobalTable` resource custom hooks, terminalCodes and e2e tests

generator.yaml, pkg/resource/backup/hooks.go, pkg/resource/backup/sdk.go, templates/hooks/backup/sdk_read_one_post_set_output.go.tpl, test/e2e/resources/backup.yaml, test/e2e/tests/test_backup.py
Part of https://github.com/aws-controllers-k8s/community/issues/803
- Add custom hooks, terminalCodes to `Backup` resource in `generator.yaml`
- Add e2e tests for `Backup` create and delete operations
=> Add `Backup` resource custom hooks, terminalCodes and e2e tests

apis/v1alpha1/ack-generate-metadata.yaml, apis/v1alpha1/backup.go, apis/v1alpha1/global_table.go, apis/v1alpha1/table.go, config/crd/bases/dynamodb.services.k8s.aws_backups.yaml, config/crd/bases/dynamodb.services.k8s.aws_globaltables.yaml, config/crd/bases/dynamodb.services.k8s.aws_tables.yaml, go.mod, go.sum, pkg/resource/backup/manager.go, pkg/resource/backup/sdk.go, pkg/resource/global_table/manager.go, pkg/resource/global_table/sdk.go, pkg/resource/table/manager.go, pkg/resource/table/sdk.go
Regenerates the DynamoDB controller with `ack-generate` v0.2.3` to get to ACK runtime v0.2.3.
By submitting this pull request, I confirm that my contribution is made under
the terms of the Apache 2.0 license.
=> Regenerates the DynamoDB controller with `ack-generate` v0.2.3

apis/v1alpha1/ack-generate-metadata.yaml, pkg/resource/backup/manager.go, pkg/resource/backup/manager_factory.go, pkg/resource/backup/resource.go, pkg/resource/backup/sdk.go, pkg/resource/global_table/manager.go, pkg/resource/global_table/manager_factory.go, pkg/resource/global_table/resource.go, pkg/resource/global_table/sdk.go, pkg/resource/table/manager.go, pkg/resource/table/manager_factory.go, pkg/resource/table/resource.go, pkg/resource/table/sdk.go
Regenerates the DynamoDB controller with `ack-generate` v0.3.1 
to bring in runtime `v0.3.0` improvements and features.
By submitting this pull request, I confirm that my contribution is made under
the terms of the Apache 2.0 license.
=> Bump runtime version and regenerates the controller with `ack-generate` v0.3.1

helm/Chart.yaml, helm/crds/dynamodb.services.k8s.aws_backups.yaml, helm/crds/dynamodb.services.k8s.aws_globaltables.yaml, helm/crds/dynamodb.services.k8s.aws_tables.yaml, helm/crds/services.k8s.aws_adoptedresources.yaml, helm/templates/cluster-role-controller.yaml, helm/templates/deployment.yaml, helm/templates/metrics-service.yaml, helm/values.yaml
Release artifacts for Dynamodb Controller `v0.0.3`.
Release includes:
- Support for `Table`, `GlobalTable`  and `Backup` resources
- Improved logging with runtime `v0.3.0`
- Documentation for CRDs and CR fields
- Metrics service to helm charts
- Fixed some issues where `Table` and `Backup` statuses weren't correctly
synced with the correct status.
- `--watch-namespace` and `--resource-tags` flags/parameters for helm
charts
By submitting this pull request, I confirm that my contribution is made under
the terms of the Apache 2.0 license.
=> release artifacts for release` v0.0.3`

apis/v1alpha1/ack-generate-metadata.yaml, cmd/controller/main.go, config/crd/bases/dynamodb.services.k8s.aws_backups.yaml, config/crd/bases/dynamodb.services.k8s.aws_globaltables.yaml, config/crd/bases/dynamodb.services.k8s.aws_tables.yaml, config/overlays/namespaced/kustomization.yaml, config/overlays/namespaced/role-binding.json, config/overlays/namespaced/role.json, go.mod, go.sum, pkg/resource/backup/delta.go, pkg/resource/backup/descriptor.go, pkg/resource/backup/manager.go, pkg/resource/backup/resource.go, pkg/resource/backup/sdk.go, pkg/resource/global_table/delta.go, pkg/resource/global_table/descriptor.go, pkg/resource/global_table/manager.go, pkg/resource/global_table/resource.go, pkg/resource/global_table/sdk.go, pkg/resource/table/delta.go, pkg/resource/table/descriptor.go, pkg/resource/table/manager.go, pkg/resource/table/resource.go, pkg/resource/table/sdk.go
Issue N/A
- Brings in ACK runtime 0.12.0
By submitting this pull request, I confirm that my contribution is made under
the terms of the Apache 2.0 license.
=> Bump runtime version and regenerate controller with ack-generate v0.12.0

apis/v1alpha1/ack-generate-metadata.yaml, apis/v1alpha1/generator.yaml, generator.yaml, helm/templates/cluster-role-controller.yaml, helm/values.schema.json, helm/values.yaml, pkg/resource/backup/manager.go, pkg/resource/global_table/manager.go, pkg/resource/table/manager.go, test/e2e/condition.py, test/e2e/tests/test_backup.py, test/e2e/tests/test_global_table.py, test/e2e/tests/test_table.py
Adds logic to the resource managers for GlobalTable, Table and
Backup resources to properly understand when
`ACK.ResourceSynced=True` condition should be applied.
Issue aws-controllers-k8s/community#1500
Signed-off-by: Jay Pipes <jaypipes@gmail.com>
By submitting this pull request, I confirm that my contribution is made
under the terms of the Apache 2.0 license.
=> update Synced condition for DDB resources

test/e2e/table.py, test/e2e/tests/test_table.py
There were two e2e tests that were flaky in
`test/e2e/tests/test_table.py`.
The flakiest test was test_enable_ttl, which often would result in the following:
```
>       assert ttl["TimeToLiveDescription"]["AttributeName"] == "ForumName"
E       KeyError: 'AttributeName'
tests/test_table.py:158: KeyError
```
This was caused by the dynamodb client `describe_time_to_live` returning
a `ResourceNotFoundException` when the Table was not in ACTIVE status
and even when the Table was in ACTIVE status, there is an amount of time
when the DescribeTimeToLive's TimeToLiveDescription output shape is
either empty or is a struct with no fields :(
I updated the test to first wait until the Table becomes ACTIVE and has
valid output responses before attempting to read the TTL information.
The second flaky …
=> rework Table e2e tests to remove flakiness

apis/v1alpha1/ack-generate-metadata.yaml, config/controller/kustomization.yaml, helm/Chart.yaml, helm/templates/NOTES.txt, helm/values.yaml, pkg/resource/global_table/sdk.go
Regenerates the controller as `v1.0.1` to include the code-generator `v0.24.2` changes. When the `v1.0.0` tag was pushed, there was no release made because of the CD cluster running out of pod resources. Therefore, `v1.0.0` was never released. I pushed out the `v1.0.0` tag again, but in that time the `v0.24.2` code-generator update pushed the version from `v0.1.9` to `v0.1.10` and included those changes.
=> release artifacts for `v1.0.1`

pkg/resource/table/hooks_global_secondary_indexes.go, pkg/resource/table/hooks_global_secondary_indexes_test.go, pkg/resource/table/sdk.go, templates/hooks/table/sdk_read_one_post_set_output.go.tpl, test/e2e/resources/table_basic_pay_per_request.yaml, test/e2e/table.py, test/e2e/tests/test_table.py
Issue #, if available:
- fix empty NonKeyAttributes validation issue
- fix GSI creation issue when using `pay-per-request` mode
```shell
2023-04-19T17:31:29.932+0200    ERROR   Reconciler error        {"controller": "table", "controllerGroup": "dynamodb.services.k8s.aws", "controllerKind": "Table", "Table": {"name":"ack-demo-table-provisioned-global-secondary-indexes","namespace":"ack-system"}, "namespace": "ack-system", "name": "ack-demo-table-provisioned-global-secondary-indexes", "reconcileID": "c7354a77-56c4-4c56-b715-f16b59d1926e", "error": "ValidationException: One or more parameter values were invalid: Neither ReadCapacityUnits nor WriteCapacityUnits can be specified when BillingMode is PAY_PER_REQUEST\n\tstatus code: 400, request id: …
```
=> Fix:  creating gsi  under on-demand mode

apis/v1alpha1/ack-generate-metadata.yaml, config/controller/kustomization.yaml, helm/Chart.yaml, helm/templates/NOTES.txt, helm/values.yaml
release v1.2.4
- fix GSI update issue when using `PAY_PER_REQUEST` mode
- set GSI capacity default to 1  when  `PROVISIONED` mode 
=> release artifacts for release v1.2.4

test/e2e/tests/test_table.py
Issue https://github.com/aws-controllers-k8s/community/issues/1920
Add e2e test for table GSIs
=> Add new e2e test case for creating GSI's with already existing attributes

apis/v1alpha1/ack-generate-metadata.yaml, config/controller/kustomization.yaml, helm/Chart.yaml, helm/templates/NOTES.txt, helm/templates/deployment.yaml, helm/values.yaml
Issue  [#1920](https://github.com/aws-controllers-k8s/community/issues/1920), if available:
- fix:  GSI can't be created for existing table without attribute definition changed. 
=> release artifacts for release v1.2.5

generator.yaml
It looks like to delete a GlobalTable we need to delete all it's region
replications. Annd with the new code-generator feature, adding support
of assigning the same AWS operation to multiple resources and CRUD
types. We'll have to explicitely set that this operation supports both
update and delete.
Signed-off-by: Amine Hilaly <hilalyamine@gmail.com>
=> Reuse UpdateGlobalTable for both Update and Delete operations

test/e2e/tests/test_table.py
It looks like we have more than one flaky test. So ideally we want to
increase the root `MODIFY_WAIT_AFTER_SECONDS` to 90 seconds.
Signed-off-by: Amine Hilaly <hilalyamine@gmail.com>
=> Increase `MODIFY_WAIT_AFTER_SECONDS` to 90

pkg/resource/table/hooks.go
fix https://github.com/aws-controllers-k8s/code-generator/pull/565
Remove getImmutableFieldChanges from hooks to support cel immutability
=> remove getImmutableFieldChanges references

apis/v1alpha1/ack-generate-metadata.yaml, pkg/resource/table/hooks.go, pkg/resource/table/hooks_replica_updates.go, pkg/resource/table/sdk.go, templates/hooks/table/sdk_delete_pre_build_request.go.tpl, templates/hooks/table/sdk_read_one_post_set_output.go.tpl, test/e2e/tests/test_table_replicas.py
Adding `TableReplica` Support as part of the minor release instead of a patch that was done and reverted.
[Original Changes]
This PR implements support for managing DynamoDB table replicas through the tableReplicas field. This enhancement allows users to manage multi-region table replicas that automatically remain in sync. This is complemented by a replicaDescription field in the Table status for tracking replica states.
Changes Overview
- Added tableReplicas field to Table spec for defining replica configurations across regions
- Added controller logic for replica lifecycle management (creation, updates, deletion)
- Implemented validation rules:
- DynamoDB Streams must be enabled with NEW_AND_OLD_IMAGES
- Terminal error conditions for invalid configurations
- E2E …
=> add TableReplica field

apis/v1alpha1/ack-generate-metadata.yaml, apis/v1alpha1/generator.yaml, apis/v1alpha1/table.go, apis/v1alpha1/zz_generated.deepcopy.go, config/crd/bases/dynamodb.services.k8s.aws_tables.yaml, generator.yaml, helm/crds/dynamodb.services.k8s.aws_tables.yaml, pkg/resource/table/delta.go, pkg/resource/table/hooks.go, pkg/resource/table/sdk.go, templates/hooks/table/sdk_create_post_set_output.go.tpl, templates/hooks/table/sdk_read_one_post_set_output.go.tpl, test/e2e/resources/table_insights.yaml, test/e2e/table.py, test/e2e/tests/test_table.py
Issue [#2408](https://github.com/aws-controllers-k8s/community/issues/2408)
=> feat: Add contributorInsights field to Table resource

config/controller/kustomization.yaml, helm/Chart.yaml, helm/templates/NOTES.txt, helm/values.yaml, pkg/resource/table/hooks.go, test/e2e/tests/test_table.py, test/e2e/tests/test_table_replicas.py
=> Release artifacts for release v1.4.0

apis/v1alpha1/ack-generate-metadata.yaml, apis/v1alpha1/generator.yaml, generator.yaml, pkg/resource/table/delta.go, pkg/resource/table/hooks.go, test/e2e/resources/table_insights.yaml, test/e2e/tests/test_table.py
These changes allow users to define both ENABLE/DISABLE and ENABLED/DISABLED value for the ContributorInsights field.
=> chore: Ensure controller understands both ENABLE & ENABLED `contributorInsights`

pkg/resource/table/hooks_tags.go
Issue [#2459#issuecomment-2886623397](https://github.com/aws-controllers-k8s/community/issues/2459#issuecomment-2886623397)
In syncTableTags, there was an issue with the order/naming of desired vs
latest resource.
Although the function is called using `syncTableTags(desired, latest)`
the function definition had `syncTableTags(latest, desired)`. This
becomes an issue when we try to retrieve the ARN from latest, during
adoption.
Although in the funciton we named the parameter `latest`, this parameter
was treated as the desired resource when computing the tags delta.
During adoption, the Status/ARN of the desired resource is meant to be 
nil, unitl it is later populated. Hence our need to use the ARN from 
latest.
By submitting this pull request, I confirm that my …
=> fix: change syncTableTags parameter order to avoid panic

apis/v1alpha1/ack-generate-metadata.yaml, pkg/resource/table/hooks.go, pkg/resource/table/sdk.go, templates/hooks/table/sdk_create_post_set_output.go.tpl, templates/hooks/table/sdk_read_one_post_set_output.go.tpl
Currently, we attempt to make certain update calls in sdkCreate, right
after we populate the resource from createOutput. These calls usually
fail as the Table may still be in `Creating` status.
Another issue that kept happening was a throttling error during sdkFind
for the DescribeTTL call. With these changes, we will be checking the
Table status and reconciling if needed, and only retrieving TTL when the
table has `available` status.
=> chore: move updates from create to sdkUpdate
